
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("7cb5fa1b-4371-46fa-984b-dfc3bbbe8255")>
#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class Database2Entities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new Database2Entities object using the connection string found in the 'Database2Entities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=Database2Entities", "Database2Entities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new Database2Entities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "Database2Entities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new Database2Entities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "Database2Entities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Headers() As ObjectSet(Of Header)
        Get
            If (_Headers Is Nothing) Then
                _Headers = MyBase.CreateObjectSet(Of Header)("Headers")
            End If
            Return _Headers
        End Get
    End Property

    Private _Headers As ObjectSet(Of Header)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Locations() As ObjectSet(Of Location)
        Get
            If (_Locations Is Nothing) Then
                _Locations = MyBase.CreateObjectSet(Of Location)("Locations")
            End If
            Return _Locations
        End Get
    End Property

    Private _Locations As ObjectSet(Of Location)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Ojeks() As ObjectSet(Of Ojek)
        Get
            If (_Ojeks Is Nothing) Then
                _Ojeks = MyBase.CreateObjectSet(Of Ojek)("Ojeks")
            End If
            Return _Ojeks
        End Get
    End Property

    Private _Ojeks As ObjectSet(Of Ojek)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Users() As ObjectSet(Of User)
        Get
            If (_Users Is Nothing) Then
                _Users = MyBase.CreateObjectSet(Of User)("Users")
            End If
            Return _Users
        End Get
    End Property

    Private _Users As ObjectSet(Of User)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Headers EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToHeaders(ByVal header As Header)
        MyBase.AddObject("Headers", header)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Locations EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToLocations(ByVal location As Location)
        MyBase.AddObject("Locations", location)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Ojeks EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToOjeks(ByVal ojek As Ojek)
        MyBase.AddObject("Ojeks", ojek)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToUsers(ByVal user As User)
        MyBase.AddObject("Users", user)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Database2Model", Name:="Header")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Header
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Header object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    ''' <param name="status">Initial value of the Status property.</param>
    Public Shared Function CreateHeader(id As Global.System.String, status As Global.System.String) As Header
        Dim header as Header = New Header
        header.Id = id
        header.Status = status
        Return header
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.String
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.String
    Private Partial Sub OnIdChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UserId() As Global.System.String
        Get
            Return _UserId
        End Get
        Set
            OnUserIdChanging(value)
            ReportPropertyChanging("UserId")
            _UserId = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("UserId")
            OnUserIdChanged()
        End Set
    End Property

    Private _UserId As Global.System.String
    Private Partial Sub OnUserIdChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnUserIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property OjekId() As Global.System.String
        Get
            Return _OjekId
        End Get
        Set
            OnOjekIdChanging(value)
            ReportPropertyChanging("OjekId")
            _OjekId = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("OjekId")
            OnOjekIdChanged()
        End Set
    End Property

    Private _OjekId As Global.System.String
    Private Partial Sub OnOjekIdChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnOjekIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property TransactionDate() As Nullable(Of Global.System.DateTime)
        Get
            Return _TransactionDate
        End Get
        Set
            OnTransactionDateChanging(value)
            ReportPropertyChanging("TransactionDate")
            _TransactionDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("TransactionDate")
            OnTransactionDateChanged()
        End Set
    End Property

    Private _TransactionDate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnTransactionDateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnTransactionDateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property From_ID() As Nullable(Of Global.System.Int32)
        Get
            Return _From_ID
        End Get
        Set
            OnFrom_IDChanging(value)
            ReportPropertyChanging("From_ID")
            _From_ID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("From_ID")
            OnFrom_IDChanged()
        End Set
    End Property

    Private _From_ID As Nullable(Of Global.System.Int32)
    Private Partial Sub OnFrom_IDChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnFrom_IDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property To_ID() As Nullable(Of Global.System.Int32)
        Get
            Return _To_ID
        End Get
        Set
            OnTo_IDChanging(value)
            ReportPropertyChanging("To_ID")
            _To_ID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("To_ID")
            OnTo_IDChanged()
        End Set
    End Property

    Private _To_ID As Nullable(Of Global.System.Int32)
    Private Partial Sub OnTo_IDChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnTo_IDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Detail() As Global.System.String
        Get
            Return _Detail
        End Get
        Set
            OnDetailChanging(value)
            ReportPropertyChanging("Detail")
            _Detail = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Detail")
            OnDetailChanged()
        End Set
    End Property

    Private _Detail As Global.System.String
    Private Partial Sub OnDetailChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDetailChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Status() As Global.System.String
        Get
            Return _Status
        End Get
        Set
            OnStatusChanging(value)
            ReportPropertyChanging("Status")
            _Status = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Status")
            OnStatusChanged()
        End Set
    End Property

    Private _Status As Global.System.String
    Private Partial Sub OnStatusChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnStatusChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Database2Model", Name:="Location")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Location
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Location object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    Public Shared Function CreateLocation(id As Global.System.Int32) As Location
        Dim location as Location = New Location
        location.Id = id
        Return location
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.Int32
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.Int32
    Private Partial Sub OnIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Location_Name() As Global.System.String
        Get
            Return _Location_Name
        End Get
        Set
            OnLocation_NameChanging(value)
            ReportPropertyChanging("Location_Name")
            _Location_Name = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Location_Name")
            OnLocation_NameChanged()
        End Set
    End Property

    Private _Location_Name As Global.System.String
    Private Partial Sub OnLocation_NameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLocation_NameChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Database2Model", Name:="Ojek")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Ojek
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Ojek object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    Public Shared Function CreateOjek(id As Global.System.String) As Ojek
        Dim ojek as Ojek = New Ojek
        ojek.Id = id
        Return ojek
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.String
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.String
    Private Partial Sub OnIdChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Firstname() As Global.System.String
        Get
            Return _Firstname
        End Get
        Set
            OnFirstnameChanging(value)
            ReportPropertyChanging("Firstname")
            _Firstname = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Firstname")
            OnFirstnameChanged()
        End Set
    End Property

    Private _Firstname As Global.System.String
    Private Partial Sub OnFirstnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFirstnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Lastname() As Global.System.String
        Get
            Return _Lastname
        End Get
        Set
            OnLastnameChanging(value)
            ReportPropertyChanging("Lastname")
            _Lastname = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Lastname")
            OnLastnameChanged()
        End Set
    End Property

    Private _Lastname As Global.System.String
    Private Partial Sub OnLastnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLastnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Email() As Global.System.String
        Get
            Return _Email
        End Get
        Set
            OnEmailChanging(value)
            ReportPropertyChanging("Email")
            _Email = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Email")
            OnEmailChanged()
        End Set
    End Property

    Private _Email As Global.System.String
    Private Partial Sub OnEmailChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnEmailChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Username() As Global.System.String
        Get
            Return _Username
        End Get
        Set
            OnUsernameChanging(value)
            ReportPropertyChanging("Username")
            _Username = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Username")
            OnUsernameChanged()
        End Set
    End Property

    Private _Username As Global.System.String
    Private Partial Sub OnUsernameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnUsernameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Password() As Global.System.String
        Get
            Return _Password
        End Get
        Set
            OnPasswordChanging(value)
            ReportPropertyChanging("Password")
            _Password = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Password")
            OnPasswordChanged()
        End Set
    End Property

    Private _Password As Global.System.String
    Private Partial Sub OnPasswordChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPasswordChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Database2Model", Name:="User")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class User
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new User object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    Public Shared Function CreateUser(id As Global.System.String) As User
        Dim user as User = New User
        user.Id = id
        Return user
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.String
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.String
    Private Partial Sub OnIdChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Firstname() As Global.System.String
        Get
            Return _Firstname
        End Get
        Set
            OnFirstnameChanging(value)
            ReportPropertyChanging("Firstname")
            _Firstname = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Firstname")
            OnFirstnameChanged()
        End Set
    End Property

    Private _Firstname As Global.System.String
    Private Partial Sub OnFirstnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFirstnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Lastname() As Global.System.String
        Get
            Return _Lastname
        End Get
        Set
            OnLastnameChanging(value)
            ReportPropertyChanging("Lastname")
            _Lastname = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Lastname")
            OnLastnameChanged()
        End Set
    End Property

    Private _Lastname As Global.System.String
    Private Partial Sub OnLastnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLastnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Email() As Global.System.String
        Get
            Return _Email
        End Get
        Set
            OnEmailChanging(value)
            ReportPropertyChanging("Email")
            _Email = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Email")
            OnEmailChanged()
        End Set
    End Property

    Private _Email As Global.System.String
    Private Partial Sub OnEmailChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnEmailChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Username() As Global.System.String
        Get
            Return _Username
        End Get
        Set
            OnUsernameChanging(value)
            ReportPropertyChanging("Username")
            _Username = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Username")
            OnUsernameChanged()
        End Set
    End Property

    Private _Username As Global.System.String
    Private Partial Sub OnUsernameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnUsernameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Password() As Global.System.String
        Get
            Return _Password
        End Get
        Set
            OnPasswordChanging(value)
            ReportPropertyChanging("Password")
            _Password = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Password")
            OnPasswordChanged()
        End Set
    End Property

    Private _Password As Global.System.String
    Private Partial Sub OnPasswordChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPasswordChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Role() As Global.System.String
        Get
            Return _Role
        End Get
        Set
            OnRoleChanging(value)
            ReportPropertyChanging("Role")
            _Role = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Role")
            OnRoleChanged()
        End Set
    End Property

    Private _Role As Global.System.String
    Private Partial Sub OnRoleChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnRoleChanged()
    End Sub

    #End Region

End Class

#End Region


